language: objective-c
cache: cocoapods
xcode_workspace: IntentKitDemo.xcworkspace
xcode_scheme: IntentKitDemo
xcode_sdk: iphonesimulator
rvm:
  - 2.2.2

before_install:
  - gem install cocoapods slather activesupport -N
  - pod install --repo-update
after_success: slather
